Affichage de donnees

TSNE (squasher les donnees en 2 dimensions) avec les donnees non binaires
Analyse correlation( 2 variables ex: type de medecin et etablissement) Montrer les correlations Attribution des poids

Listes des techniques a essayer pour le pre-traitement(reductions de dimensionnalite):
- Debinariser les donnees et le transformer en dataset de pytorch

Listes des techniques a essayer pour le deep learning:
- Deep Clustering Network (DCN)
- Deep Embedding Network (DEN)
- Deep Subspace Clustering Networks (DSC-Nets)
- Deep Nonparametric Clustering (DNC) (Non-supervise)
- Deep Nonparametric Clustering (DNC) (Non-supervise)

Listes des techniques a essayer pour le clustering:
- K-Means
- Expection maximum
- DB scan
- Mean shift clustering
- Agglomerative Hierarchical Clustering

In [5]:
import numpy

In [50]:
import pickle

infile = open('trainDatasetPerdiem-20191028.pkl', 'rb')
data, labels = pickle.load(infile)
print(labels)
infile.close()



Variable                        Possibilités             Nombre de colonne (+1)
Spécialité de médecins	        33 codes de spécialité	        1-33
Sexe de médecin 	            2	                            34-35
Langue de correspondance 	    2	                            36-37
Université de graduation 	    14 universités	                38-51
Plage horaire de facturation	3 (AM, PM, toute la journée)	52-54
Agence de représentation	    845 codes d’agences             55-899
Établissements                  241 établissements	            900-1140
ActeMedical                     2 (Oui et Non)	                1141-1142
Activités médico-admin          2 (Oui et Non)	                1143-1144
Activités d’enseignement	    2 (Oui et Non)	                1145-1146
Entente LE	                    2 (Oui et Non)	                1147-1148
Activité en santé communautaire	2 (Oui et Non)	                1149-1150
Activité en santé comm. CSST	2 (Oui et Non)	                1151-1152
Activité en santé 

In [95]:
# prints Data type for reference
# print(type(data))

numberOfRows = 5
beginningOfColumns = 0
endOfColumns = 32

# isolate the first 5 rows and first 32 columns
isolatedDataByRows = data.head(numberOfRows)
piece = isolatedDataByRows.iloc[:, beginningOfColumns : endOfColumns]

np_array = numpy.asarray(piece.to_numpy())
print(np_array)

debinarized = [0 for c in range(numberOfRows)]

for i, value in enumerate(np_array):
    for index, binaryValue in enumerate(value):
        debinarized[i] += index * binaryValue
        
print(debinarized)



[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[5, 2, 19, 19, 12]
