Affichage de donnees

TSNE (squasher les donnees en 2 dimensions) avec les donnees non binaires
Analyse correlation( 2 variables ex: type de medecin et etablissement) Montrer les correlations Attribution des poids

Listes des techniques a essayer pour le pre-traitement(reductions de dimensionnalite):
- Debinariser les donnees et le transformer en dataset de pytorch

Listes des techniques a essayer pour le deep learning:
- Deep Clustering Network (DCN)
- Deep Embedding Network (DEN)
- Deep Subspace Clustering Networks (DSC-Nets)
- Deep Nonparametric Clustering (DNC) (Non-supervise)
- Deep Nonparametric Clustering (DNC) (Non-supervise)

Listes des techniques a essayer pour le clustering:
- K-Means
- Expection maximum
- DB scan
- Mean shift clustering
- Agglomerative Hierarchical Clustering

In [5]:
import numpy

In [1]:
import pickle

infile = open('trainDatasetPerdiem-20191028.pkl', 'rb')
data, labels = pickle.load(infile)
print(labels)
infile.close()

FileNotFoundError: [Errno 2] No such file or directory: 'trainDatasetPerdiem-20191028.pkl'

In [95]:
# prints Data type for reference
# print(type(data))

numberOfRows = 5
beginningOfColumns = 0
endOfColumns = 32

# isolate the first 5 rows and first 32 columns
isolatedDataByRows = data.head(numberOfRows)
piece = isolatedDataByRows.iloc[:, beginningOfColumns : endOfColumns]

np_array = numpy.asarray(piece.to_numpy())
print(np_array)

debinarized = [0 for c in range(numberOfRows)]

for i, value in enumerate(np_array):
    for index, binaryValue in enumerate(value):
        debinarized[i] += index * binaryValue
        
print(debinarized)



[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[5, 2, 19, 19, 12]
